#!/bin/bash
### BEGIN INIT INFO
# Provides:          bibliologs
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start and stop the bibliolog application
### END INIT INFO

cd /applis/bibliolog/home

bibliolog_start() {
  NODE_ENV=production forever start --uid 'log.io-server' -a -o ./logs/log.io-server-stdout.log -e ./logs/log.io-server-stderr.log $(which log.io-server)

  NODE_ENV=production forever start --uid 'ezpaarse2log.io' -a -o ./logs/ezpaarse2log.io-stdout.log -e ./logs/ezpaarse2log.io-stderr.log ./ezpaarse2log.io/app.js
}

bibliolog_stop() {
  forever stop 'log.io-server'
  forever stop 'ezpaarse2log.io'
}

bibliolog_status() {
  forever list | grep 'log.io-server'
  forever list | grep 'ezpaarse2log.io'
}

case $1 in

  start)
    bibliolog_start
  ;;

  stop)
    bibliolog_stop
  ;;
  
  restart)
    bibliolog_stop
    sleep 1
    bibliolog_start
  ;;

  status)
    bibliolog_status
  ;;

  *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
  ;;

esac





